"""Initial schema

Revision ID: 6f7671d5daac
Revises: 
Create Date: 2026-09-18 20:08:09.622326

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6f7671d5daac'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contact_messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('subject', sa.String(length=255), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('NEW', 'READ', 'RESPONDED', name='contactstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('contact_messages', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_contact_messages_id'), ['id'], unique=False)

    op.create_table('lab_tests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('normal_range', sa.String(length=100), nullable=True),
    sa.Column('unit', sa.String(length=50), nullable=True),
    sa.Column('price', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('lab_tests', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_lab_tests_code'), ['code'], unique=True)
        batch_op.create_index(batch_op.f('ix_lab_tests_id'), ['id'], unique=False)

    op.create_table('medicines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('generic_name', sa.String(length=100), nullable=False),
    sa.Column('dosage_form', sa.String(length=50), nullable=False),
    sa.Column('strength', sa.String(length=50), nullable=False),
    sa.Column('stock_quantity', sa.Integer(), nullable=False),
    sa.Column('reorder_level', sa.Integer(), nullable=False),
    sa.Column('unit_price', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('medicines', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_medicines_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_medicines_name'), ['name'], unique=False)

    op.create_table('services',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('icon_name', sa.String(length=50), nullable=True),
    sa.Column('department', sa.String(length=100), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('services', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_services_code'), ['code'], unique=True)
        batch_op.create_index(batch_op.f('ix_services_id'), ['id'], unique=False)

    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('PATIENT', 'DOCTOR', 'ADMIN', name='userrole'), nullable=False),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_role'), ['role'], unique=False)

    op.create_table('activity_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('entity_type', sa.String(length=100), nullable=True),
    sa.Column('entity_id', sa.Integer(), nullable=True),
    sa.Column('details', sa.Text(), nullable=True),
    sa.Column('ip_address', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('activity_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_activity_logs_action'), ['action'], unique=False)
        batch_op.create_index(batch_op.f('ix_activity_logs_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_activity_logs_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_activity_logs_user_id'), ['user_id'], unique=False)

    op.create_table('doctors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('specialty', sa.String(length=100), nullable=False),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.Column('room_number', sa.String(length=50), nullable=True),
    sa.Column('qualifications', sa.String(length=255), nullable=True),
    sa.Column('available_days', sa.String(length=100), nullable=True),
    sa.Column('consultation_fee', sa.Integer(), nullable=True),
    sa.Column('photo_url', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('doctors', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_doctors_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_doctors_specialty'), ['specialty'], unique=False)
        batch_op.create_index(batch_op.f('ix_doctors_user_id'), ['user_id'], unique=True)

    op.create_table('password_reset_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('token_hash', sa.String(length=255), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('used', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('password_reset_tokens', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_password_reset_tokens_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_password_reset_tokens_token_hash'), ['token_hash'], unique=False)
        batch_op.create_index(batch_op.f('ix_password_reset_tokens_user_id'), ['user_id'], unique=False)

    op.create_table('appointments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('doctor_id', sa.Integer(), nullable=False),
    sa.Column('appointment_date', sa.String(length=20), nullable=False),
    sa.Column('time_slot', sa.String(length=20), nullable=False),
    sa.Column('status', sa.Enum('SCHEDULED', 'COMPLETED', 'CANCELLED', 'NO_SHOW', name='appointmentstatus'), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['doctor_id'], ['doctors.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['patient_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('appointments', schema=None) as batch_op:
        batch_op.create_index('ix_appointment_doctor_date_slot', ['doctor_id', 'appointment_date', 'time_slot'], unique=False)
        batch_op.create_index(batch_op.f('ix_appointments_appointment_date'), ['appointment_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_appointments_doctor_id'), ['doctor_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_appointments_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_appointments_patient_id'), ['patient_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_appointments_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_appointments_time_slot'), ['time_slot'], unique=False)

    op.create_table('emergency_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patient_name', sa.String(length=255), nullable=False),
    sa.Column('patient_phone', sa.String(length=50), nullable=False),
    sa.Column('severity', sa.Enum('CRITICAL', 'HIGH', 'MEDIUM', 'LOW', name='emergencyseverity'), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('WAITING', 'IN_TREATMENT', 'RESOLVED', name='emergencystatus'), nullable=False),
    sa.Column('assigned_doctor_id', sa.Integer(), nullable=True),
    sa.Column('triage_notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['assigned_doctor_id'], ['doctors.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('emergency_requests', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_emergency_requests_assigned_doctor_id'), ['assigned_doctor_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_emergency_requests_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_emergency_requests_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_emergency_requests_severity'), ['severity'], unique=False)
        batch_op.create_index(batch_op.f('ix_emergency_requests_status'), ['status'], unique=False)
        batch_op.create_index('ix_emergency_severity_status_created', ['severity', 'status', 'created_at'], unique=False)

    op.create_table('lab_orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('doctor_id', sa.Integer(), nullable=False),
    sa.Column('test_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('ORDERED', 'SAMPLE_COLLECTED', 'COMPLETED', name='laborderstatus'), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('result_text', sa.Text(), nullable=True),
    sa.Column('result_value', sa.String(length=100), nullable=True),
    sa.Column('is_abnormal', sa.Boolean(), nullable=False),
    sa.Column('sample_collected_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['doctor_id'], ['doctors.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['patient_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['test_id'], ['lab_tests.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('lab_orders', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_lab_orders_doctor_id'), ['doctor_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_lab_orders_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_lab_orders_patient_id'), ['patient_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_lab_orders_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_lab_orders_test_id'), ['test_id'], unique=False)

    op.create_table('prescriptions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('doctor_id', sa.Integer(), nullable=False),
    sa.Column('diagnosis', sa.String(length=255), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'FILLED', 'EXPIRED', 'CANCELLED', name='prescriptionstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['doctor_id'], ['doctors.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['patient_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('prescriptions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_prescriptions_doctor_id'), ['doctor_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_prescriptions_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_prescriptions_patient_id'), ['patient_id'], unique=False)

    op.create_table('prescription_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('prescription_id', sa.Integer(), nullable=False),
    sa.Column('medicine_id', sa.Integer(), nullable=False),
    sa.Column('dosage', sa.String(length=100), nullable=False),
    sa.Column('frequency', sa.String(length=100), nullable=False),
    sa.Column('duration', sa.String(length=100), nullable=False),
    sa.Column('instructions', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['medicine_id'], ['medicines.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['prescription_id'], ['prescriptions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('prescription_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_prescription_items_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_prescription_items_medicine_id'), ['medicine_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_prescription_items_prescription_id'), ['prescription_id'], unique=False)

    op.create_table('refill_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('prescription_id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('REQUESTED', 'APPROVED', 'REJECTED', 'DISPENSED', name='refillstatus'), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['prescription_id'], ['prescriptions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('refill_requests', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_refill_requests_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_refill_requests_patient_id'), ['patient_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_refill_requests_prescription_id'), ['prescription_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('refill_requests', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_refill_requests_prescription_id'))
        batch_op.drop_index(batch_op.f('ix_refill_requests_patient_id'))
        batch_op.drop_index(batch_op.f('ix_refill_requests_id'))

    op.drop_table('refill_requests')
    with op.batch_alter_table('prescription_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_prescription_items_prescription_id'))
        batch_op.drop_index(batch_op.f('ix_prescription_items_medicine_id'))
        batch_op.drop_index(batch_op.f('ix_prescription_items_id'))

    op.drop_table('prescription_items')
    with op.batch_alter_table('prescriptions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_prescriptions_patient_id'))
        batch_op.drop_index(batch_op.f('ix_prescriptions_id'))
        batch_op.drop_index(batch_op.f('ix_prescriptions_doctor_id'))

    op.drop_table('prescriptions')
    with op.batch_alter_table('lab_orders', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_lab_orders_test_id'))
        batch_op.drop_index(batch_op.f('ix_lab_orders_status'))
        batch_op.drop_index(batch_op.f('ix_lab_orders_patient_id'))
        batch_op.drop_index(batch_op.f('ix_lab_orders_id'))
        batch_op.drop_index(batch_op.f('ix_lab_orders_doctor_id'))

    op.drop_table('lab_orders')
    with op.batch_alter_table('emergency_requests', schema=None) as batch_op:
        batch_op.drop_index('ix_emergency_severity_status_created')
        batch_op.drop_index(batch_op.f('ix_emergency_requests_status'))
        batch_op.drop_index(batch_op.f('ix_emergency_requests_severity'))
        batch_op.drop_index(batch_op.f('ix_emergency_requests_id'))
        batch_op.drop_index(batch_op.f('ix_emergency_requests_created_at'))
        batch_op.drop_index(batch_op.f('ix_emergency_requests_assigned_doctor_id'))

    op.drop_table('emergency_requests')
    with op.batch_alter_table('appointments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_appointments_time_slot'))
        batch_op.drop_index(batch_op.f('ix_appointments_status'))
        batch_op.drop_index(batch_op.f('ix_appointments_patient_id'))
        batch_op.drop_index(batch_op.f('ix_appointments_id'))
        batch_op.drop_index(batch_op.f('ix_appointments_doctor_id'))
        batch_op.drop_index(batch_op.f('ix_appointments_appointment_date'))
        batch_op.drop_index('ix_appointment_doctor_date_slot')

    op.drop_table('appointments')
    with op.batch_alter_table('password_reset_tokens', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_password_reset_tokens_user_id'))
        batch_op.drop_index(batch_op.f('ix_password_reset_tokens_token_hash'))
        batch_op.drop_index(batch_op.f('ix_password_reset_tokens_id'))

    op.drop_table('password_reset_tokens')
    with op.batch_alter_table('doctors', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_doctors_user_id'))
        batch_op.drop_index(batch_op.f('ix_doctors_specialty'))
        batch_op.drop_index(batch_op.f('ix_doctors_id'))

    op.drop_table('doctors')
    with op.batch_alter_table('activity_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_activity_logs_user_id'))
        batch_op.drop_index(batch_op.f('ix_activity_logs_id'))
        batch_op.drop_index(batch_op.f('ix_activity_logs_created_at'))
        batch_op.drop_index(batch_op.f('ix_activity_logs_action'))

    op.drop_table('activity_logs')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_role'))
        batch_op.drop_index(batch_op.f('ix_users_id'))
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    with op.batch_alter_table('services', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_services_id'))
        batch_op.drop_index(batch_op.f('ix_services_code'))

    op.drop_table('services')
    with op.batch_alter_table('medicines', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_medicines_name'))
        batch_op.drop_index(batch_op.f('ix_medicines_id'))

    op.drop_table('medicines')
    with op.batch_alter_table('lab_tests', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_lab_tests_id'))
        batch_op.drop_index(batch_op.f('ix_lab_tests_code'))

    op.drop_table('lab_tests')
    with op.batch_alter_table('contact_messages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_contact_messages_id'))

    op.drop_table('contact_messages')
    # ### end Alembic commands ###
